import daisyui from "daisyui";

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./renderer/index.html", "./renderer/src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [daisyui],
  daisyui: {
    themes: [
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",
      // ── Custom WhatsApp theme ──────────────────────────────────────────
      {
        whatsapp: {
          primary: "#00A884",
          "primary-content": "#ffffff",
          secondary: "#8696A0",
          "secondary-content": "#ffffff",
          accent: "#25D366",
          "accent-content": "#ffffff",
          neutral: "#2A3942",
          "neutral-content": "#E9EDEF",
          "base-100": "#111B21",
          "base-200": "#202C33",
          "base-300": "#2A3942",
          "base-content": "#E9EDEF",
          info: "#53BDEB",
          success: "#00A884",
          warning: "#F0C849",
          error: "#F15C6D",
        },
      },
      // ── Custom Video Call theme ──────────────────────────────────────────
      {
        videocall: {
          primary: "#00A884",
          "primary-content": "#ffffff",
          secondary: "#8696A0",
          "secondary-content": "#ffffff",
          accent: "#00A884",
          "accent-content": "#ffffff",
          neutral: "#2A3942",
          "neutral-content": "#E9EDEF",
          "base-100": "#111B21",
          "base-200": "#0B141A",
          "base-300": "#2A3942",
          "base-content": "#E9EDEF",
          info: "#53BDEB",
          success: "#00A884",
          warning: "#F0C849",
          error: "#F15C6D",
        },
      },
    ],
  },
};
